name: 'Deploy Kube-Prom-Stack'
description: 'A GitHub Action to deploy Prometheus'
inputs:
  name:
    description: 'Name of the user'
    required: true
outputs:
  greeting:
    description: 'The greeting message'
runs:
  using: 'composite'
  steps:
    - run: |
        echo "HELLO ${{ inputs.name }}"
      shell: bash
